---
- hosts: all
  become: yes

  tasks:
    - name: Deploy traefik
      community.docker.docker_container:
        name: traefik
        image: "traefik:v2.5"
        ports:
          - "80:80"
          - "443:443"
          - "8080:8080"
        volumes:
          - /run/docker.sock:/run/docker.sock
          - /etc/traefik:/etc/traefik
        restart_policy: unless-stopped